sudo: false

language: node_js
node_js:
  - 10.16.0

script:
  - npm run lint
  - npm run build

env:
  VUE_APP_API_URL="https://jsonplaceholder.typicode.com/"

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "pirate-demo"
  api_key:
    secure: "3fad0554-9abe-49c2-a064-8e66089c666e"
