sudo: false

language: node_js
node_js:
  - 10.16.0

script:
  - npm run lint
  - npm run build

env:
  VUE_APP_API_URL="https://jsonplaceholder.typicode.com/"

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "pirate-demo"
  api_key:
    secure: "533b1219-f078-4c2c-b85f-385aed8bc250"
