sudo: false
env:
  DEPLOY_TO=github-pages
  VUE_APP_API_URL="https://jsonplaceholder.typicode.com/"

language: node_js
node_js:
  - 10.16.0

install:
  - npm ci

script:
  - npm run lint
  - npm run test:unit
  - npm run build

branches:
  only:
    - master

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
#
# deploy to Heroku
# deploy:
#   provider: heroku
#   app: "pirate-demo"
#   api_key:
#     secure: "533b1219-f078-4c2c-b85f-385aed8bc250"
