sudo: false

language: node_js
node_js:
  - 10.16.0

script:
  - npm run lint

env:
  VUE_APP_API_URL=https://jsonplaceholder.typicode.com/

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "pirate-demo"
  api_key:
    secure: "ee66975d-0155-4652-ba45-435fd67d8e4d"
