language: node_js

node_js:
  - 'node:latest'

cache: npm

script:
  - npm run deploy

env:
  - NODE_ENV=production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
